#spring:
#  security:
#    oauth2:
#      authorizationserver:
#        client:
#          client-1:
#            #require-authorization-consent: true
#            registration:
#              client-id: "client"
#              # the client secret is "secret" (without quotes)
#              client-secret: "{bcrypt}$2a$10$jdJGhzsiIqYFpjJiYWMl/eKDOd8vdyQis2aynmFN0dgJ53XvpzzwC"
#              client-authentication-methods: "client_secret_jwt"
#              authorization-grant-types: "client_credentials,authorization_code,refresh_token"
#              redirect-uris: http://localhost:8082/login/oauth2/code/spring
#              scopes: "user.read,user.write,openid"
#            token:
#              access-token-time-to-live: 30s
logging:
  level:
    org.springframework.security: trace
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/oauth2
    username: postgres
    password: qwerqwer
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
